export const routes = {
  chat: '/chat',
  quickReplies: '/quick-replies',
  rolesPermissions: '/roles-permissions',
  roles: '/roles',
  permissions: '/permissions',
  phoneNumbers: '/phone-numbers',
  contacts: '/contacts',
  apiManagement: '/api-management',
  messageQueues: '/message-queues',
  analytics: '/analytics',
  users: '/users',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/sign-in',
  templates: {
    dashboard: '/templates',
    create: '/templates/create',
    edit: (id: string) => `/templates/${id}/edit`,
  },
  templateRoles: '/template-roles',
};
